---
excludes:
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Packages provided at runtime by the JDK or container only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: 'devDependencies'
    reason: 'DEV_DEPENDENCY_OF'
    comment: 'Packages for development only.'
  paths:
  - pattern: "bin/**"
    reason: "BUILD_TOOL_OF"
    comment: "Tool for license checking"
package_configurations:
- id: "NPM::spdx-licenses:0.0.3"
  source_artifact_url: "https://registry.npmjs.org/spdx-licenses/-/spdx-licenses-0.0.3.tgz"
  license_finding_curations:
  - path: "package/spdx.json"
    concluded_license: 'CC0-1.0'
    reason: 'DATA_OF'
    comment: >-
      This file contains official SPDX.org license ids. SPDX is licensed under CC0-1.0, see
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33.
- id: "NPM::spdx-ranges:1.0.1"
  source_artifact_url: "https://registry.npmjs.org/spdx-ranges/-/spdx-ranges-1.0.1.tgz"
  license_finding_curations:
  - path: "package/index.json"
    concluded_license: 'CC0-1.0'
    reason: 'DATA_OF'
    comment: >-
      This file contains official SPDX.org license ids. SPDX is licensed under CC0-1.0, see
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33.
- id: "NPM::spdx-expression-parse:1.0.4"
  source_artifact_url: "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz"
  license_finding_curations:
  - path: "package/parser.js"
    concluded_license: 'CC0-1.0'
    reason: 'DATA_OF'
    comment: >-
      This file contains official SPDX.org license ids. SPDX is licensed under CC0-1.0, see
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33.
- id: "NPM::spdx:0.5.2"
  source_artifact_url: "https://registry.npmjs.org/spdx/-/spdx-0.5.2.tgz"
  license_finding_curations:
  - path: "package/parser.js"
    concluded_license: 'CC0-1.0'
    reason: 'DATA_OF'
    comment: >-
      This file contains official SPDX.org license ids. SPDX is licensed under CC0-1.0, see
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33.
resolutions:
  vulnerabilities:
  - id: "sonatype-2020-1349"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Already fixed in this version"
  - id: "CVE-2022-37865"
    reason: "MITIGATED_VULNERABILITY"
    comment: "Mitigated by PR123"
  - id: "CVE-2022-37866"
    reason: "INVALID_MATCH_VULNERABILITY"
    comment: "Scanner did identify wrong component"
